# Generated by Django 3.2.6 on 2022-02-06 01:14

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=cpf_field.models.CPFField(max_length=11, null=True, unique=True, verbose_name='CPF'),
        ),
    ]
